AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description:
  Node.js barebone for AWS Lambda
Globals:
  Function:
    Timeout: 300
    Runtime: nodejs14.x
    MemorySize: 512
Resources:
  MainFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: index.handleEvent
